NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Models/BannerModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NguyenDinhHoangLan_BaiTap5.Models
{
    public class BannerModel
    {
        [Required(ErrorMessage = "Không được bỏ trống ảnh")]
        [DisplayName("Chọn ảnh làm banner: ")]
        public string banner { get; set; }
    }
}

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Models/EmpModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NguyenDinhHoangLan_BaiTap5.Models
{
    public class EmpModel
    {
        [Required(ErrorMessage = "Không được bỏ trống trường này")]
        [DisplayName("Mã số nhân viên")]
        public string EmpID { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống trường này")]
        [DisplayName("Họ tên")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống trường này")]
        [DisplayName("Ngày sinh")]
        public DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống trường này")]
        [DisplayName("Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống trường này")]
        [DisplayName("Mật khẩu")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống trường này")]
        [DisplayName("Đơn vị")]
        public string Department { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống ảnh")]
        [DisplayName("Ảnh đại diện")]
        public string Avatar { get; set; }
    }
}

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Models/MailInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NguyenDinhHoangLan_BaiTap5.Models
{
    public class MailInfo
    {
        [Required(ErrorMessage = "Không được bỏ trống trường này")]
        [DisplayName("Gửi từ Email")]
        public string From { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống trường này")]
        [DisplayName("Mật khẩu")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống trường này")]
        [DisplayName("Gửi đến Email")]
        public string To { get; set; }
        [DisplayName("Tiêu đề")]
        public string Subject { get; set; }
        [DisplayName("Nội dung")]
        public string Body { get; set; }
    }
}

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NguyenDinhHoangLan_BaiTap5.Models;

namespace NguyenDinhHoangLan_BaiTap5.Controllers
{
    public class BannerController : Controller
    {
        // GET: Banner
        public ActionResult Banner()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Banner(BannerModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            HttpPostedFileBase Banner = Request.Files[0];
            if (Banner.ContentLength > 0)
            {
                string fileName = System.IO.Path.GetFileName(Banner.FileName);
                var path = Server.MapPath("/Images/" + fileName);
                Banner.SaveAs(path);
                string fSave = Server.MapPath("/banner.txt");
                System.IO.File.WriteAllText(fSave, fileName);

                ViewBag.image = "/Images/" + fileName;
            }
            return View();
        }
    }
}

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NguyenDinhHoangLan_BaiTap5.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NguyenDinhHoangLan_BaiTap5.Controllers
{
    public class LayoutController : Controller
    {
        // GET: Layout
        public ActionResult Home()
        {
            return View();
        }

        public ActionResult Mail()
        {
            return View("../Mail/Mail");
        }

        public ActionResult Register()
        {
            return View("../Register/Index");
        }
        public ActionResult Banner()
        {
            return View("../Banner/Banner");
        }
    }
}

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Controllers/MailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NguyenDinhHoangLan_BaiTap5.Models;

namespace NguyenDinhHoangLan_BaiTap5.Controllers
{
    public class MailController : Controller
    {
        // GET: Mail
        public ActionResult Mail()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Mail(MailInfo model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            System.Net.Mail.MailMessage mail = new System.Net.Mail.MailMessage();
            mail.From = new System.Net.Mail.MailAddress(model.From);
            mail.To.Add(model.To);
            mail.Subject = model.Subject;
            mail.Body = model.Body;
            mail.IsBodyHtml = true;
            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient("smtp.gmail.com", 587);
            smtp.Credentials = new System.Net.NetworkCredential(model.From, model.Password);
            smtp.EnableSsl = true;
            smtp.Send(mail);
            return View("Mail");
        }
    }
}

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NguyenDinhHoangLan_BaiTap5.Models;

namespace NguyenDinhHoangLan_BaiTap5.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(EmpModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            HttpPostedFileBase Avatar = Request.Files[0];
            if (Avatar.ContentLength > 0)
            {

                string postedFileName = System.IO.Path.GetFileName(Avatar.FileName);

                string path = Server.MapPath("/Images/") + postedFileName;
                Avatar.SaveAs(path);
                string fSave = Server.MapPath("/info.txt");
                string[] emInfo =
                    {model.EmpID,
                    model.Name,
                    model.DateOfBirth.ToShortDateString(),
                    model.Email,
                    model.Password,
                    model.Department,
                    postedFileName
                };
                System.IO.File.WriteAllLines(fSave, emInfo);

                model.EmpID = emInfo[0];
                model.Name = emInfo[1];
                model.DateOfBirth = model.DateOfBirth;
                model.Email = emInfo[3];
                model.Password = emInfo[4];
                model.Department = emInfo[5];
                model.Avatar = "/Images/" + emInfo[6];
            }
            return View("Confirm", model);
        }
        public ActionResult Confirm(EmpModel emp)
        {
            return View(emp);
        }
    }
}

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Views/Banner/Banner.cshtml
@model NguyenDinhHoangLan_BaiTap5.Models.BannerModel

@{
    ViewBag.Title = "Banner";
    Layout = "~/Views/Shared/_ Bt5Layout.cshtml";
}

<link href="~/Content/RegisterStyle.css" rel="stylesheet" type="text/css" />

@using (Html.BeginForm("Banner", "Banner", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="box row">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div style="width: 100%; text-align:center; margin-bottom: 1.5em;"><h4>THAY ĐỔI BANNER</h4></div>
        <hr />

        <div class="col-lg-4">@Html.LabelFor(model => model.banner, htmlAttributes: new { @class = "control-label float-right-lg" })</div>
        <div class="col-lg-8">
            @Html.TextBoxFor(model => model.banner, new { type = "file" })<br />
            @Html.ValidationMessageFor(model => model.banner, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-4"></div>
        <div class="col-lg-8">
            <input type="submit" value="Thay đổi" class="btn btn-default" />
        </div>
    </div>    
}

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Views/Layout/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_ Bt5Layout.cshtml";
}

TRANG CHU

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Views/Register/Confirm.cshtml
@{
    ViewBag.Title = "Confirm";
    Layout = "~/Views/Shared/_ Bt5Layout.cshtml";
}

<link href="~/Content/RegisterStyle.css" rel="stylesheet" type="text/css" />

@using (Html.BeginForm("Confirm", "Register", FormMethod.Post))
{
    <div class="row box">
        <div style="width: 100%; text-align:center; margin-bottom: 1.5em;"><h4>THÔNG TIN THÀNH VIÊN ĐÃ ĐĂNG KÝ</h4></div>
        <hr />
        <div class="col-lg-5"><img src="@Model.Avatar" /></div>

        <div class="col-lg-7 row">
            <div class="col-lg-4">Mã nhân viên:</div>
            <div class="col-lg-8">@Model.EmpID</div>
            <br />
            <div class="col-lg-4">Họ tên:</div>
            <div class="col-lg-8">@Model.Name</div>
            <br />
            <div class="col-lg-4">Ngày sinh:</div>
            <div class="col-lg-8">@Model.DateOfBirth.ToShortDateString()</div>
            <br />
            <div class="col-lg-4">Email:</div>
            <div class="col-lg-8">@Model.Email</div>
            <br />
            <div class="col-lg-4">Mật khẩu:</div>
            <div class="col-lg-8">@Model.Password</div>
            <br />
            <div class="col-lg-4">Đơn vị:</div>
            <div class="col-lg-8">@Model.Department</div>
            <br />
            <div class="col-lg-4"><a href="@Url.Action("Index", "Register")">Quay lại</a></div>
        </div>

    </div>
}

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Views/Register/Index.cshtml
@model NguyenDinhHoangLan_BaiTap5.Models.EmpModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ Bt5Layout.cshtml";
}

<link href="~/Content/RegisterStyle.css" rel="stylesheet" type="text/css" />

@using (Html.BeginForm("Index", "Register", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="box row">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div style="width: 100%; text-align:center; margin-bottom: 1.5em;"><h4>THÔNG TIN THÀNH VIÊN ĐĂNG KÝ</h4></div>
        <hr />

        <div class="col-lg-4 center-label">@Html.LabelFor(model => model.EmpID)</div>
        <div class="col-lg-8">
            @Html.TextBoxFor(model => model.EmpID, new { htmlAttributes = new { @class = "" } })<br />
            @Html.ValidationMessageFor(model => model.EmpID, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-4 center-label">@Html.LabelFor(model => model.Name)</div>
        <div class="col-lg-8">
            @Html.TextBoxFor(model => model.Name, new { htmlAttributes = new { @class = "" } })<br />
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-4 center-label">@Html.LabelFor(model => model.DateOfBirth)</div>
        <div class="col-lg-8">
            @Html.TextBoxFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "" } })<br />
            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-4 center-label">@Html.LabelFor(model => model.Email)</div>
        <div class="col-lg-8">
            @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "" } })<br />
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-4 center-label">@Html.LabelFor(model => model.Password)</div>
        <div class="col-lg-8">
            @Html.TextBoxFor(model => model.Password, new { htmlAttributes = new { @class = "" } })<br />
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-4 center-label">@Html.LabelFor(model => model.Department)</div>
        <div class="col-lg-8">
            @Html.TextBoxFor(model => model.Department, new { htmlAttributes = new { @class = "" } })<br />
            @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-4 center-label">@Html.LabelFor(model => model.Avatar)</div>
        <div class="col-lg-8">
            @Html.TextBoxFor(model => model.Avatar, new { type = "file" })
            @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger", id = "custom-upload" })
        </div>

        <div class="col-lg-4"></div>
        <div class="col-md-8">
            <input type="submit" value="Đăng ký" class="my-btn" />
        </div>

    </div>
}

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Views/Shared/_ Bt5Layout.cshtml
@{ 
    var path = Server.MapPath("/banner.txt");
    var fileImage = System.IO.File.ReadAllText(path);
    ViewBag.image = "/Images/" + fileImage;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/MailStyle.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/RegisterStyle.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-3.3.1.js" type="text/javascript"></script>
</head>
<body>
    <div>
        <img class="banner" src="@ViewBag.image" />
    </div>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li class="active">@Html.ActionLink("TRANG CHỦ", "Home", "Layout", "", htmlAttributes: new { @class = "" })</li>
                <li>@Html.ActionLink("ĐĂNG KÝ", "Register", "Layout", "", htmlAttributes: new { @class = "" })</li>
                <li>@Html.ActionLink("GỬI EMAIL", "Mail", "Layout", "", htmlAttributes: new { @class = "" })</li>
                <li>@Html.ActionLink("THAY ĐỔI BANNER", "Banner", "Layout", "", htmlAttributes: new { @class = "" })</li>
            </ul>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
    <footer>
        Copyright &copy; LÂN   @DateTime.Now.ToShortDateString()
    </footer>
</body>
</html>

NguyenDinhHoangLan_BaiTap5/NguyenDinhHoangLan_BaiTap5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>